### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by honza** [adamwiggins/12factor#10]
Hi, this is more of a question about what you're proposing. In a situation where your application is composed of several independent services, how do you handle authentication? How can you make sure that all the components are looking at the same user session/data? I'm a Python guy: what if you have two small Django-based services and you need to make sure that they are both looking at the same `User` object?

Any pointers would be appreciated

**Comment by adamwiggins** [comment]
A central identity provider such as OAuth is the emerging best-practice here.  Two apps reading the same database and sharing user model code (e.g. `User`) is generally a bad idea.
