### ISSUE TITLE
Link is outdated

### ISSUE THREAD

**Issue by Boiarshinov** [adamwiggins/12factor#40]
[This](https://dustin.github.com/2010/02/28/running-processes.html) link in [Concurenncy](https://github.com/adamwiggins/12factor/blob/master/content/concurrency.md) factor description not alive anymore.

> Twelve-factor app processes [should never daemonize](https://dustin.github.com/2010/02/28/running-processes.html) or write PID files.

Can anyone find active link and replace the broken one?

**Comment by jamietanna** [comment]
See https://github.com/heroku/12factor/pull/296 - the repo is now managed by Heroku's upstream

**Comment by Boiarshinov** [comment]
Thanks!
Very sad to see that these 2 repos doesn't mantained anymore
